import 'package:flutter/material.dart';

final darkTheme = ThemeData(
  accentColor: Color(0xFF167BD9),
  appBarTheme: AppBarTheme(
    brightness: Brightness.dark,
    elevation: 0,
    color: Color(0xFF282828).withOpacity(0.9),
  ),
  bottomNavigationBarTheme: BottomNavigationBarThemeData(
    selectedItemColor: Color(0xFFF5F5F5),
    unselectedItemColor: Color(0xFF878787),
    elevation: 0,
    backgroundColor: Color(0xFF282828).withOpacity(0.7),
    selectedLabelStyle: TextStyle(
      fontFamily: 'PT Root UI',
      fontWeight: FontWeight.normal,
      fontSize: 12,
      height: 16.0 / 12.0,
    ),
    unselectedLabelStyle: TextStyle(
      fontFamily: 'PT Root UI',
      fontWeight: FontWeight.normal,
      fontSize: 12,
      height: 16.0 / 12.0,
    ),
  ),
  textTheme: TextTheme(
    headline1: TextStyle(
      color: Color(0xFFF5F5F5),
      fontFamily: 'PT Root UI',
      fontWeight: FontWeight.w600,
      fontSize: 16,
      height: 24 / 16,
      letterSpacing: 0.15,
    ),
    headline2: TextStyle(
      color: Color(0xFFF5F5F5),
      fontFamily: 'PT Root UI',
      fontWeight: FontWeight.w600,
      fontSize: 16,
      height: 24 / 16,
      letterSpacing: 0.15,
    ),
    headline3: TextStyle(
      color: Color(0xFFF5F5F5),
      fontFamily: 'PT Root UI',
      fontWeight: FontWeight.normal,
      fontSize: 14,
      letterSpacing: 0.1,
      height: 24 / 14,
    ),
    headline4: TextStyle(
      color: Color(0xFFF5F5F5).withOpacity(0.6),
      fontFamily: 'PT Root UI',
      fontWeight: FontWeight.normal,
      fontSize: 12,
      height: 16.0 / 12.0,
    ),
    headline5: TextStyle(
      color: Color(0xFFF5F5F5),
      fontFamily: 'PT Root UI',
      fontWeight: FontWeight.w600,
      fontSize: 20,
      height: 24.0 / 20.0,
      letterSpacing: 0.15,
    ),
    headline6: TextStyle(
      fontFamily: 'Fira Sans',
      fontSize: 18,
      height: 1.3,
      color: Color(0xFFF5F5F5),
    ),
    bodyText1: TextStyle(
      color: Color(0xFFF5F5F5),
      fontFamily: 'Gotham Pro',
      fontWeight: FontWeight.normal,
      fontSize: 12,
      height: 16.0 / 12.0,
    ),
    bodyText2: TextStyle(
      fontFamily: 'Fira Sans',
      fontSize: 14,
      height: 1.3,
      color: Color(0xFFF5F5F5),
    ),
    subtitle1: TextStyle(
      color: Color(0xFFF5F5F5).withOpacity(0.55),
      fontFamily: 'PT Root UI',
      fontWeight: FontWeight.normal,
      fontSize: 12,
      height: 16.0 / 12.0,
    ),
  ),
  primaryColor: Color(0xFF282828),
  scaffoldBackgroundColor: Color(0xFF282828),
  visualDensity: VisualDensity.adaptivePlatformDensity,
);

final lightTheme = ThemeData(
  appBarTheme: AppBarTheme(
    brightness: Brightness.light,
    elevation: 0,
    color: Color(0xFFF5F5F5).withOpacity(0.8),
  ),
  bottomNavigationBarTheme: BottomNavigationBarThemeData(
    selectedItemColor: Color(0xFF1E1E1E),
    unselectedItemColor: Color(0xFF878787),
    elevation: 0,
    backgroundColor: Color(0xFFF5F5F5).withOpacity(0.6),
    selectedLabelStyle: TextStyle(
      fontFamily: 'PT Root UI',
      fontWeight: FontWeight.normal,
      fontSize: 12,
      height: 16.0 / 12.0,
    ),
    unselectedLabelStyle: TextStyle(
      fontFamily: 'PT Root UI',
      fontWeight: FontWeight.normal,
      fontSize: 12,
      height: 16.0 / 12.0,
    ),
  ),
  textTheme: TextTheme(
    headline1: TextStyle(
      color: Color(0xFF282828),
      fontFamily: 'PT Root UI',
      fontWeight: FontWeight.w600,
      fontSize: 16,
      height: 24 / 16,
      letterSpacing: 0.15,
    ),
    headline2: TextStyle(
      color: Color(0xFF1E1E1E),
      fontFamily: 'PT Root UI',
      fontWeight: FontWeight.w600,
      fontSize: 16,
      height: 24 / 16,
      letterSpacing: 0.15,
    ),
    headline3: TextStyle(
      color: Color(0xFF282828),
      fontFamily: 'PT Root UI',
      fontWeight: FontWeight.normal,
      fontSize: 14,
      letterSpacing: 0.1,
    ),
    headline4: TextStyle(
      color: Color(0xFF1E1E1E).withOpacity(0.6),
      fontFamily: 'PT Root UI',
      fontWeight: FontWeight.normal,
      fontSize: 12,
      height: 16.0 / 12.0,
    ),
    headline5: TextStyle(
      color: Color(0xFF282828),
      fontFamily: 'PT Root UI',
      fontWeight: FontWeight.w500,
      fontSize: 20,
      height: 24.0 / 20.0,
      letterSpacing: 0.15,
    ),
    headline6: TextStyle(
      fontFamily: 'Fira Sans',
      fontSize: 18,
      height: 1.3,
      color: Color(0xFF282828),
    ),
    bodyText1: TextStyle(
      color: Color(0xFF282828),
      fontFamily: 'PT Root UI',
      fontWeight: FontWeight.normal,
      fontSize: 12,
      height: 16.0 / 12.0,
    ),
    bodyText2: TextStyle(
      fontFamily: 'Fira Sans',
      fontSize: 14,
      height: 1.3,
      color: Color(0xFF282828),
    ),
    subtitle1: TextStyle(
      color: Color(0xFF282828).withOpacity(0.55),
      fontFamily: 'PT Root UI',
      fontWeight: FontWeight.normal,
      fontSize: 12,
      height: 16.0 / 12.0,
    ),
  ),
  accentColor: Color(0xFF167BD9),
  primaryColor: Color(0xFFF5F5F5),
  scaffoldBackgroundColor: Color(0xFFF1F1F1),
  visualDensity: VisualDensity.adaptivePlatformDensity,
);
